sonar.projectKey=Xmisra_NIT-HOSTEL-V2
sonar.organization=xmisra

sonar.projectName=NIT-HOSTEL-V2
sonar.sourceEncoding=UTF-8

# Analyze frontend + backend
sonar.sources=backend,src

# Exclude unnecessary folders
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

# Do NOT analyze env or config secrets
sonar.coverage.exclusions=**/*.test.js,**/*.spec.js
