
services:
  
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306


  app:
    build: .
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: db
      DB_DIALECT: ${DB_DIALECT}
      NODE_ENV: ${NODE_ENV}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_LOGGING: ${DB_LOGGING}
    ports:
      - "3000:3000"

volumes:
  db_data:    



